#!/bin/bash

options=(
	style=rounded
  blacklist="Kando,iPhone Mirroring,Screen Studio, CleanMyMac X"
	width=7.0
	hidpi=off
  active_color=0xffea9a97
	inactive_color=0xFF44415a
)

borders "${options[@]}"
